### ISSUE TITLE
Being assigned projects that I have already reviewed

### ISSUE THREAD

**Issue by jaintj95** [OpenMined/courses-app#100]
## Description
I just completed reviewing a project. When I clicked on Assign , I got assigned the same project that I finished reviewing 2 mins ago.

**Comment by ITsolution-git** [comment]
This is mainly becuase same project with same content submitted twice. The "Submit" button should be disabled once it's submitted to prevent it to be clicked twice. If then, there will be exactly same content, and from mentor's point of view, he is assigned same project.
