### ISSUE TITLE
Unable to access previous reviews and submissions for projects which were "failed"

### ISSUE THREAD

**Issue by sumeetsgit** [OpenMined/courses-app#101]
I got assigned one submission for review today which was "failed" by a previous reviewer for some reasons(which I am not able to see).
Now, this person has resubmitted his assignment with a rebuttal of some of the comments of the previous reviewer. The problem I face now is that I do not see/have access to the older review and hence cannot comment anything on this rebuttal.
Essentially, I need access to all the previous reviews and submissions.

**Comment by tcp** [comment]
This is fixed and tested in dev. Should be live soon.

Thanks @sumeetsgit.
