### ISSUE TITLE
Projects stuck in my queue even though review time has expired

### ISSUE THREAD

**Issue by jaintj95** [OpenMined/courses-app#104]
![locked](https://user-images.githubusercontent.com/36858630/106719104-e49a3080-6627-11eb-978e-537d32162a0d.png)

These reviews are stuck in my queue since yesterday.

**Comment by ITsolution-git** [comment]
@tcp 
checkForUnreviewedSubmissions runs every 30 mins..  Those reviews stuck because checkForUnreviewedSubmissions failed somehow. Can you find some errors on checkForUnreviewedSubmissions of production db and send it to me?

**Comment by tcp** [comment]
Hey @jaintj95 I went back in time and I couldn't replicate this. I assume that this is not the case anymore.

Sorry we couldn't catch this one. Let us know if happens again.
