### ISSUE TITLE
Mentor cannot review assignment after being assigned a student project

### ISSUE THREAD

**Issue by hwrdtm** [OpenMined/courses-app#111]
## Description
As a mentor, I am unable to review an assignment after having been assigned a student project.

## How to Reproduce

1. Log in
2. Enable Mentor mode
3. Click `Assign` in the project queue for `Our Privacy Opportunity`
4. Click `Review` under `Your Reviews` section
5. Browser visits the student project page very briefly before automatically redirected back to the mentor dashboard at https://courses.openmined.org/users/dashboard

## Expected Behavior

As a mentor I should be able to visit the student's project submission without being redirected away.

## System Information
 - OS: `macOS`
 - OS Version: `10.15.4`
 - Browser (if applicable): `Brave`
 - Browser Version (if applicable): `Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64)`

**Comment by ITsolution-git** [comment]
@tcp 
This is the duplication of https://github.com/OpenMined/openmined/issues/99.

As long as there is a submission with more than 4 submissions, reviewers will keep get assigned to that review and this error will be persistent.

Can we find those students/courses with more than 3 submissions in users/courses/{id}/submissions collection and remove one with id greater than 3?

**Comment by tcp** [comment]
Cool, I'll go over the db and I'll fix it there. :)

**Comment by tcp** [comment]
Removed the last dangling refs yesterday, should be 100% fixed.
