### ISSUE TITLE
Create a `stats` collection

### ISSUE THREAD

**Issue by tcp** [OpenMined/courses-app#114]
## Feature Description
Create a stats collection that allow us to have a quick glance at the numbers from the courses platform.

Initially, we can create a collection that covers:

```js
{
  activeUsers, // number of users with active accounts
  totalSubmissions, // total number of submissions per course
  totalReviews, // total number of reviews made
  totalPassed, // total number of students that passed the project
  totalFailed, // total number of students that did not pass the project submission
  avgTimeToReview, // avg time for reviewing a submission
  acceptanceRate // acceptance rate of projects per each submission phase
}
```

**Comment by ITsolution-git** [comment]
@tcp 
Can you specify if totalReviews/totalPassed/totalFailed/avgTimeToReview is per course? Or just total thoughout the courses... Or both?

https://github.com/OpenMined/openmined/pull/89/files collects information of pending/failed submissions by course.
It's the totalSubmissions...

It collects in courses/{courseName}/numPendingSubmissions
![image](https://user-images.githubusercontent.com/24530559/109483141-df74a980-7a4c-11eb-92c6-6c8169815876.png)

**Comment by tcp** [comment]
Per course basis, but stored in the new collection.
