### ISSUE TITLE
Apply mentor review rules in firebase

### ISSUE THREAD

**Issue by tcp** [OpenMined/courses-app#117]
## Description
We need to edit two rules in the cloud function:

1. Mentors can only review 1 assignment at a time
2. Mentors should not be allocated the same assignment they resigned from

Add both to the submission alloc function.

**Comment by curt-mitch** [comment]
@tcp Can you add some details on what the "pending review" rule covers?

**Comment by tcp** [comment]
Sure @curt-mitch, sorry for not updating this sooner. I'll add to the description.

**Comment by ITsolution-git** [comment]
Whoops, unassigning myself since I just saw curtis comments. Thanks!
(BTW - I guess we need to save the history of assignments user resigned from. So that it doesn't assign it again)
