### ISSUE TITLE
Ensure Mentors completion displays 100% in the Dashboard

### ISSUE THREAD

**Issue by tcp** [OpenMined/courses-app#122]
It's showing 98%.

**Comment by curt-mitch** [comment]
@tcp Is this referring to the course completion percentage or some other value in the dashboard?

**Comment by tcp** [comment]
@curt-mitch completion percentage

**Comment by curt-mitch** [comment]
On a first pass the logic to compute the percentage seems fine and hasn't changed recently:
https://github.com/OpenMined/openmined/blob/bc022805f5afbc098756310e3d7e724b8562aa6e/apps/courses/src/components/CourseProgressCard.tsx#L20

Is it possible that the recent changes to the construction of the course (mentioned here: https://openmined.slack.com/archives/C01HY1GAG76/p1615398252029000) are causing this issue?

**Comment by tcp** [comment]
No, unfortunately it is not linked.

I'll try to gather more info. I've seen in passing the 98% issue, but I'll see if I can replicate.
