### ISSUE TITLE
Progress is lost after changes to syllabus structure

### ISSUE THREAD

**Issue by nigoshh** [OpenMined/courses-app#126]
## Description
During the last 24 hours, the structure of the course syllabus was changed. Now there are more lessons. For example, some concept videos were moved from Lesson 2 to Lesson 3 and Lesson 4 (you can see this from the titles of the videos on YouTube, which still reflect the old syllabus structure). Progress information on some of the concepts was not kept after the restructuring, i.e. videos which were previously watched and marked as such, are now unmarked. For me, this happened to all the videos of Lesson 3, 4 and 7 (lesson numbers in the current structure).

## How to Reproduce
Cannot really reproduce it, as it was a consequence of restructuring the syllabus.

## Expected Behavior
Progress information is kept after restructuring the syllabus, so that students are not left wondering whether the unmarked videos are actually new videos, and they can avoid going through all the unmarked videos to check that they have already seen them (and mark them again).

**Comment by tcp** [comment]
@nigoshh thank you for reporting this. We're on it.

**Comment by tcp** [comment]
Fixed.

If you have issues with the progress, please post in the discussion board.
