### ISSUE TITLE
"Next" button not working when zoom level is 120% or higher

### ISSUE THREAD

**Issue by nigoshh** [OpenMined/courses-app#139]
## Description
In the Foundations of Private Computation course, Lesson 1 (Federated Learning), Concept 13 (Duet Exercises: Setup), the "Next" button cannot be clicked; hovering over it shows the text "Scroll down and make sure to complete all quiz questions first!". 

## How to Reproduce
Set your browser's zoom level at 120% or higher (I can reproduce it with 2 different browsers).

## Expected Behavior
The button works at all zoom levels.

**Comment by tcp** [comment]
Fixed in #142
