### ISSUE TITLE
Tiny spelling mistake in project submission confirmation

### ISSUE THREAD

**Issue by nvw1** [OpenMined/courses-app#143]
## Description
It says 'Out' instead of 'Our mentors' on in the confirmation displayed after submitting a project. (https://courses.openmined.org/courses/our-privacy-opportunity/project)

## How to Reproduce
1. Go to 'https://courses.openmined.org/courses/our-privacy-opportunity/project'
2. Submit a project
3. Scroll down to the end of the page
4. Click the blue box where it says to write your proposal.
5. Text pops up Starting with "Thank you for your submission! **Out** mentors will..."

## Expected Behavior
"Our" instead of "Out"

## System Information
 - OS: OSX

**Comment by tcp** [comment]
Thank you @nvw1, I'll ship this in the next batch.
