### ISSUE TITLE
Dashboard UI

### ISSUE THREAD

**Issue by tcp** [OpenMined/courses-app#151]
Readability and hierarchy are off.

- [x]  Increase shadow visibility either through reducing blur or decreasing transparency or could add faint gray outline to white cards. Card is currently not clearly defined from the background
- [x]  Increase line spacing between concepts on resume card
- [x]  Make it to where "resume" card only shows 3 concepts. The top two being what the student just finished and the 3rd being what they are currently working on
- [x]  Make it to where the user can click on a concept line within the "Resume" card and be directed to that specific concept
- [x]  Have the concepts underline on hover
- [x]  Have the Course name underline on hover

**Comment by ITsolution-git** [comment]
@tcp 
> Make it to where "resume" card only shows 3 concepts. The top two being what the student just finished and the 3rd being what they are currently working on

We now show lessons on resume cards not concepts. Should we change this behavior?

**Comment by tcp** [comment]
> We now show lessons on resume cards not concepts. Should we change this behavior?

Yes.

And the display cases should be one of the following:

```
1 | 2 | 3 | 4
--------------
u | f | f | f
u | u | f | f
u | u | u | f
```

`u`: unfinished concept
`f`: finished concept

**Comment by ITsolution-git** [comment]
@tcp I got that point.

I was asking if we are now showing concepts instead of lessons on that resume card.

**Comment by tcp** [comment]
> We now show lessons on resume cards not concepts. Should we change this behavior?
> I was asking if we are now showing concepts instead of lessons on that resume card.

Yes, that's the change :)

**Comment by ITsolution-git** [comment]
![image](https://user-images.githubusercontent.com/24530559/114085217-137a9000-987f-11eb-8f4d-0f24a2386a3a.png)

It now shows the last 2 completed concepts (if any) and next available concept (if any).
If all concepts are completed, it will show the project at the end.
