### ISSUE TITLE
Remove @ts-ignore issues

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/courses-app#3]
## Description
Right now we have some Typescript errors in the courses website that I've commented out using the `// @ts-ignore` flag. Likewise, I've allowed this rule in the ESLint configuration as well. I'd like to remove that rule in ESLint, and fix all the Typescript linting errors. You can find all of these issues by doing a project search for `@ts-ignore`. Below is a current list of the one's that exist in the codebase:

**apps/courses/src/routes/homepage/Footer.tsx**
```jsx
// @ts-ignore
const uniqueMembers = Array.from(
  new Set(finalMembers.map(JSON.stringify)),
  JSON.parse
);
```

**apps/courses/src/components/forms/_form.tsx**
```jsx
// @ts-ignore
elem = <FieldArray {...input} control={control} register={register} />;
```

**apps/courses/src/components/forms/_form.tsx**
```jsx
// @ts-ignore
fields.forEach(({ name, defaultValue }) => {
  defVals[name] = defaultValue;
});
```

**apps/courses/src/index.tsx**
```jsx
// @ts-ignore
import { unstable_createRoot } from 'react-dom';
```

## Are you interested in working on this improvement yourself?
- No, it's an open issue!

**Comment by HarshCasper** [comment]
Hello @cereallarceny 

I would like to work on this Issue if it's still open!

**Comment by cereallarceny** [comment]
Let's chat on Slack - DM me
