### ISSUE TITLE
Github authorization requires access to both public and private repos

### ISSUE THREAD

**Issue by kirbiyik** [OpenMined/courses-app#5]
## Question
Why it is necessary to access private repos?

## Screenshots
If applicable, add screenshots to help explain your question
.
<img width="498" alt="Screen Shot 2020-11-13 at 17 41 48" src="https://user-images.githubusercontent.com/16326440/99084780-6f92fe00-25d8-11eb-9d48-8cd9ddc6e3ce.png">

## System Information
 - OS: MacOS

**Comment by cereallarceny** [comment]
I've changed this to just be public now @kirbiyik . We want to see how our community re-engage with contributing to our codebase after taking some courses. Everything we do is open-source, literally all of it. So I promise you there was no nefarious intent. Closing this issue now.
