### ISSUE TITLE
Prevent mentors from being reassigned to the same review they just resigned from

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/courses-app#58]
Self-explanatory

**Comment by curt-mitch** [comment]
@tcp It seems like some of the work this task needs is covered in PR https://github.com/OpenMined/openmined/pull/89, specifically fetching the mentor reviews with status `resigned` from Firebase in `apps/firebase-api/src/app/review.ts` which resolves issue https://github.com/OpenMined/openmined/issues/60. 

Should we wait until that PR is merged before starting this task to avoid duplicated work or merge conflicts?

**Comment by ITsolution-git** [comment]
@curt-mitch 
I worked on that PR and I confirm that there wont be duplicated work here. But since two PRs will work on same file review.ts, there will definitely be conflicts.... ;)
CC @tcp

**Comment by tcp** [comment]
See #117.
