### ISSUE TITLE
Rewrite the helpers functions

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/courses-app#62]
Write the course helpers functions in the order in which they need to appear (per the flow of the course, not grouped by topic). That will make those rules much more readable. Secondly, you should ensure that the tests build on each other (i.e. testing completion of a lesson means testing the completion of all previous lessons and their respective concepts). You may need to modify the tests for this significantly.

**Comment by tcp** [comment]
This could be closed by #85. I'll check if we have to do some extra leg work here.
