### ISSUE TITLE
Lesson 2: Data is fire - Website crashes on answering quiz

### ISSUE THREAD

**Issue by jaintj95** [OpenMined/courses-app#69]
## Description
Website crashes on answering quiz

## How to Reproduce
1. Go to Lesson 2: Data is fire 
2. Click on the right answer for quiz 1 (all of the above)
3. Website crashes

## Screenshots
![image](https://user-images.githubusercontent.com/36858630/103462906-92c36980-4d4e-11eb-8886-cdbe469ec365.png)

**Comment by jaintj95** [comment]
I am unable to progress with the course because the next lessons won't load unless I answer the quiz. 
Maybe the quizzes can be made optional temporarily until all the bugs are ironed out.

**Comment by cereallarceny** [comment]
This has been fixed, please hard refresh. Closing.
