### ISSUE TITLE
Fail to login with github on firefox

### ISSUE THREAD

**Issue by adrinjalali** [OpenMined/courses-app#70]
## Description
Trying to log in to courses.openmined.org, on firefox, with adblockers installed and third party cookies disabled, I see this: 

![Screenshot from 2021-01-02 18-22-41](https://user-images.githubusercontent.com/1663864/103463113-47975f80-4d2a-11eb-9881-7131771db7f2.png)

This account is already linked with GH, using chrome, and loging in on chrome works.

Trying to set a password while logged in on chrome doesn't work and gives an authentication error. But one can reset (or rather set) a password for the email while not logged in, using firefox, and once the password is set, one can log in with the email/password using either browsers.

After doing this, still trying to connect the GH account on firefox fails with the same error.

## System Information
 - OS: linux
 - OS Version: archlinux
 - Browser (if applicable): firefox
 - Browser Version (if applicable): 84.0.1-1

cc: @cereallarceny

**Comment by cereallarceny** [comment]
Please follow the instructions listed in the #courses channel on Slack:

1. Make sure you’re logged out first.
2. Go to the /signup page
3. Sign up again (using the email/password signup, not Github) with the SAME email you use to login to Github
4. Once signed up and logged in, go to the account settings page: /users/settings
5. Go to Manage Account
6. Unlink your Github account
7. Re-link your Github account
8. At this point, you’ll be able to login using either Github or email/password in the future and the issue should be fixed

**Comment by adrinjalali** [comment]
Except that Step 7 would result in the same failure. I cannot re-link my GH account on FF.
