### ISSUE TITLE
Bug on Quiz Choices in Lesson Data is Fire 

### ISSUE THREAD

**Issue by nahuakang** [OpenMined/courses-app#71]
## Description
On [lesson 2: data is fire](https://courses.openmined.org/courses/our-privacy-opportunity/1f34d3a8-2fa1-4a1e-9ef1-eaaf9dddd617/fcf32a04-4bfe-4f84-be84-e540ff653d30), I cannot click the last 2 multiple choices for the quiz (one of which is the correct answer).

## How to Reproduce
1. Go to [lesson 2: data is fire](https://courses.openmined.org/courses/our-privacy-opportunity/1f34d3a8-2fa1-4a1e-9ef1-eaaf9dddd617/fcf32a04-4bfe-4f84-be84-e540ff653d30)
2. Click on either of the last two choices
3. Your webpage will crash

## Expected Behavior
I should be able to select the correct choice and move on to the next quiz (5 in total).

## Screenshots
N/A

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by cereallarceny** [comment]
This has already been fixed, please hard refresh.
