### ISSUE TITLE
Allow view access to project module even when previous lesson modules are not fully complete

### ISSUE THREAD

**Issue by jaintj95** [OpenMined/courses-app#72]
## Description
Being able to access and view the project module and full project instructions helps keep everything in mind while working through the course such that you can iteratively build your project while going through the course.

What I mean by that is, usually for any course I pursue, I go through the project module and check out all the instructions and guidelines and note them down. Then while going through the course material I jot down ideas to implement in the project.
(I am sure some other learners follow this approach too)

So until the course lessons are completed, you can provide view only access to project module. Right now, I can only see an overview on the course homepage

**Comment by cereallarceny** [comment]
We provide project descriptions and parts on the course overview page: https://courses.openmined.org/courses/our-privacy-opportunity
