### ISSUE TITLE
OpenMined Course 1 Lesson 2 "Conflict, Political Science & Information Flows" Missing A Clip

### ISSUE THREAD

**Issue by nahuakang** [OpenMined/courses-app#73]
## Description
[This video](https://youtu.be/xIn54pBRHyA) from 11:53 to 11:58 misses a clip of a real-world example of a 3rd party facilitating the mediation to avoid nuclear actions from India and Pakistan.

## How to Reproduce
Check out the video.

## Expected Behavior
The example from the guest lecturer should be inserted.

## Screenshots
N/A

## System Information
N/A

## Additional Context
N/A

**Comment by nahuakang** [comment]
@em-blue @mcleonard

**Comment by 4mber** [comment]
@iamtrask

**Comment by cereallarceny** [comment]
Thanks for the report @nahuakang ! Unfortunately, this is an issue with content. I'm going to ask that you instead post this on the courses discussion board, while I close this issue. I'd like to reserve Github issues to strictly be technical in nature.

https://github.com/OpenMined/courses/discussions
