### ISSUE TITLE
Top and bottom bar take up screen estate and reduce content visibility.

### ISSUE THREAD

**Issue by jaintj95** [OpenMined/courses-app#74]
## Description

The top and bottom bar are huge and end up taking quite a significant amount of screen space and therefore even cut through video content. 
Maybe the top bar can be auto-hidden since it has no functional use when going through the lessons. 
Size of bottom bar could also be reduced.

**Comment by cereallarceny** [comment]
Fair enough, we can look into this @jaintj95 , but keep in mind you can also just make the video full-screen in your browser. 😄

**Comment by cereallarceny** [comment]
I'm going to defer this to our design team. Closing for now.
