### ISSUE TITLE
Video Bug: The Copy Problem

### ISSUE THREAD

**Issue by nahuakang** [OpenMined/courses-app#75]
## Description
[Lesson 3 The Copy Problem](https://youtu.be/nwbtX9rr_L0) from 9:01 to 9:19, Cory Doctorow talked about the copy problem as a double-edged sword and then decided that he wanted to start over again and proceeded to provide a better explanation.

## How to Reproduce
1. Go to video at the specified timestamp

## Expected Behavior
1. Remove the repeated content from 9:01 to 9:19
2. Add the appropriate animation of Cory's name from 9:19 onward for a brief moment.

## Screenshots
N/A

## System Information
N/A

## Additional Context
N/A

**Comment by nahuakang** [comment]
@iamtrask

**Comment by cereallarceny** [comment]
Thanks for the report @nahuakang ! Unfortunately, this is an issue with content. I'm going to ask that you instead post this on the courses discussion board, while I close this issue. I'd like to reserve Github issues to strictly be technical in nature.

https://github.com/OpenMined/courses/discussions
