### ISSUE TITLE
Pressing "enter" on Sign In will trigger the Github Login

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/courses-app#8]
When we hit the "enter" or "return" key on the sign in form, it triggers the Github login instead of the "Sign In" button. This is a bit confusing, and ironically, does the exact opposite for the sign up form. So the sign up form works as intended, but sign up doesn't... despite being basically identical code.

**Comment by ITsolution-git** [comment]
@cereallarceny  I cannot reproduce the issue. I fill email/password and type 'enter', it triggers "Sign in" not "sign in with github"
