### ISSUE TITLE
Broken link: "Exposed: the tricks sellers use to post fake reviews on Amazon"

### ISSUE THREAD

**Issue by replomancer** [OpenMined/courses-app#84]
## Description
Hey,
I found a broken link in Additional Resources (Lesson 2, Concept 10).
I hope it's the right place to report this (technical issue).

## How to Reproduce
1. Go to Lesson 2, Concept 10, Feedback Mechanisms & Information Flows
2. Click on "Exposed: the tricks sellers use to post fake reviews on Amazon"
3. The link is broken (:robot: Robot says, "Oops!").

## Additional Context
Some extra text at the end of url needs to be deleted.

**Comment by cereallarceny** [comment]
This is a content issue, please post it on the discussion board: https://github.com/OpenMined/courses/discussions
