### ISSUE TITLE
Mentor Dashboard Tabs have higher zindex than navbar

### ISSUE THREAD

**Issue by ITsolution-git** [OpenMined/courses-app#88]
![image](https://user-images.githubusercontent.com/24530559/105078515-2047ce80-5a5c-11eb-9f2c-d9af2b1e0471.png)

The tab should not have higher z index than navbar

**Comment by curt-mitch** [comment]
Edit: nevermind, I found a way to reproduce this. Working on a fix!

~~Hi @ITsolution-git, can you confirm this is still an issue and maybe provide more context if that's the case? I'm having trouble reproducing this~~
