### ISSUE TITLE
Throwing error when trying to log into the course

### ISSUE THREAD

**Issue by MrFord123** [OpenMined/courses-app#91]
## Description
When attempting to log into the openmined course i was thrown the following error.

## How to Reproduce
1. Go to the https://courses.openmined.org/signin
2. Click on Sign in with Github
3. Enter Github credential

## Expected Behavior
Should have signed me into the course

## Screenshots
![image](https://user-images.githubusercontent.com/13626562/105150343-90a62c80-5afc-11eb-9baa-a6b12aa5f5b5.png)

## System Information
 - OS: Windows 10
 - Browser: Google Chrome

## Additional Context
I have tried on multiple browsers but still the same error unfortunately

**Comment by ITsolution-git** [comment]
@MrFord123 
When you signup, did you use email/password? Or you have only used github for signup/signin?

**Comment by MrFord123** [comment]
I have used the github signin/signup

**Comment by ITsolution-git** [comment]
Wow, that was quite fast ;)

I was able to reproduce the issue, I think you have used email/password when you signup. And now you are trying github with the same email.
The error message "An account already exists .... Signin using a provider using the provider associated with this email" bascially means the provider associated with your email is email/password provider. Not github provider.


Next steps for you:
1. Login email/password.  If you forgot password, do reset using "Forget password"
2. After you login sucessfully, go to "Account settings" of your profile. You will see connect github. Click it to connect github with your current account


Next steps for us
The error message is expected but  the success message should be removed. Will will work on that.

**Comment by MrFord123** [comment]
Thank you. This resolved the issue perfectly
