### ISSUE TITLE
Final Project Submission

### ISSUE THREAD

**Issue by Kjeanclaude** [OpenMined/courses-app#93]
## Description
There was a problem during the "Final Project: Create a Privacy Product Specification" submission. Surely due to an internet connexion latence, the project had been submited three (03) times during the first submission. While I was expecting a review before other possible submissions. I think there is the need for a control of a review before additional submissions.

## How to Reproduce
1. Go to 'https://courses.openmined.org/courses/our-privacy-opportunity/project'
2. Click on the 'Submit' button under the 'Write Your Proposal' tab
3. On the popup that appears click on the 'Continue' button (2 or 3 times to simulate the internet latence)

## Expected Behavior
There should be a control to prevent from additional submissions before a review.
For a first submission, the number of attempts should be '1 of 3 attempts'. 

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]
 - Browser (if applicable): [e.g. Google Chrome]
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by tcp** [comment]
Hey @Kjeanclaude! Better late than never -- this has been fixed and is being deployed tonight.
