### ISSUE TITLE
Unable to review project

### ISSUE THREAD

**Issue by jaintj95** [OpenMined/courses-app#99]
## Description
Unable to review project as I keep getting redirected back to dashboard when I click on the Review button.

## How to Reproduce
Clicking on review button loads the project but then redirects me back to the dashboard.

Also, when I resign from a review and then try to assign a new review, I am assigned the same review as before and that one keeps me redirecting me to the dashboard.

**Comment by tcp** [comment]
It's been a while and I couldn't replicate. Checked the logs for Feb 1st, nothing. Very unfortunate. :(

> Clicking on review button loads the project but then redirects me back to the dashboard.

@ITsolution-git is this fixed by the stricter submission button?

>Also, when I resign from a review and then try to assign a new review, I am assigned the same review as before and that one keeps me redirecting me to the dashboard.

Similar to #58

**Comment by ITsolution-git** [comment]
@tcp 
Yes. It probably because of that lose submit button.
User was able to create more then submissions in submissions collection. And if the dashboard/Mentor.js catches the error with mismatching submission, it redirects back to dashboard...

So yes.
